#!/usr/bin/env bash
#change local host with 127.0.0.2
#facebook.com change it to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "172.0.0.2       localhost" > ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
